### ISSUE TITLE
Some error when train the net

### ISSUE THREAD

**Issue by Jinbo-Zuo** [iSEE-Laboratory/EconomicGrasp#2]
I followed the instructions in the readme and ran the training program, but the following error occurred:
`FileNotFoundError: [Errno 2] No such file or directory: 'path_to_data/graspness/scene_0013/realsense/0170.npy'`
However, in folder "graspness", I only have scene_0100 to scene_0129, because in generate_graspness.py you wrote that
`for scene_id in range(100, 130): ...`
Is there anything wrong here? Or should I modify it to 0-190 in generate_graspness.py?
Or, can you open source the pre-trained model trained on the GraspNet dataset? Thanks

**Comment by DravenALG** [comment]
Yes. It's my problem. 

It should be 0-100 (101-190 are not needed in training). I already revise the code.

I will open source a checkpoint in the near future.

**Comment by DravenALG** [comment]
Checkpoint is already uploaded.
