### ISSUE TITLE
请问有没有像graspnet一样的demo.py的代码可以测试一下现实场景？

### ISSUE THREAD

**Issue by fertiliz** [iSEE-Laboratory/EconomicGrasp#6]

**Comment by DravenALG** [comment]
由于现实场景的设备不尽相同，很难提供一个通用的demo代码来进行测试。

实际上您可以根据需要，修改测试的代码text.py以达到目的。

1. 只需要将“line-26: Create dataset and dataloader”那一段换成您对应的从深度相机获取的点云。

2. 然后“line-78: grasp_preds = pred_decode(end_points)”的结果便是模型输出抓手的集合，对应格式为[N, grasp_score, grasp_width, grasp_height, grasp_depth, grasp_rotation(3*3 rotation), grasp_center, obj_ids]，您对这个集合的抓手根据score分数排序，然后选出top1的抓手然后转换成对应的格式放到您机械臂对应的api中即可运行。

**Comment by DravenALG** [comment]
当然还需要进行合适的坐标系转换，来统一坐标系，模型输出的抓手是在相机坐标系下的，要转换到机械臂坐标系才能放到api中。

**Comment by fertiliz** [comment]
谢谢！

**Comment by fertiliz** [comment]
很不错的工作，以下是我尝试和graspnet-baseline做了以下对比。
![截图 2024-12-23 16-36-47](https://github.com/user-attachments/assets/26999dfb-fea1-4dbb-b7dc-aa48a84bfe95)
左边是EcoGrasp，右边是Graspnet

**Comment by DravenALG** [comment]
可以可以！感谢支持
